### PR TITLE
correction of portrange checking

### PR DESCRIPTION
**Pull request by dneuhaeuser**
configured port needs checking against sysctl parameter "net.inet.ip.portrange.reservedhigh" instead of "net.inet.ip.portrange.first".

### CODE REVIEW

**Comment by phil-davis** [comment]
On pfSense 2.1.5 and 2.2.2 I get:
net.inet.ip.portrange.reservedhigh: 1023
net.inet.ip.portrange.first: 1024
So it seems to me it does not really matter which is used, as long as the comparison is correct.
Using net.inet.ip.portrange.first the current "<" test is correct (anything <1024 is a bad idea), but the error text "must contain a port number higher than 1024" is slightly wrong - the port number could also be equal to 1024.
Using net.inet.ip.portrange.reservedhigh the error text turns out right - "must contain a port number higher than 1023). But the test needs to be <= otherwise the current code here will allow the user to put port 1023.

**Comment by dneuhaeuser** [comment]
you're right that both sysctl values are the same in pfSense 2.1.x and 2.2.x.
BUT: apparently the underlying freebsd in pfSense 2.2.x behaves differently.
processes without root-rights cannot listen on ports <= reservedhigh value anymore!

so the value that needs to be adjusted to do this is: "net.inet.ip.portrange.reservedhigh"
changing "net.inet.ip.portrange.first" does not help at all.

and you're right: the comparison needs to be <=.

example:
to let squid reverse proxy listen to port 443
system tunable "net.inet.ip.portrange.reservedhigh" needs to be set to 442.

**Comment by rbgarga** [comment]
In order to have your patches accepted, you must sign Individual or Corporate CLA as described at https://www.pfsense.org/about-pfsense/#legal

Also please bump package version on pkg_config.xml files so users can see there is an update available

**Comment by dneuhaeuser** [comment]
ok, both done!

**Pull request merged**
