### PR TITLE
Adding support for Google Authenticator

### PR DESCRIPTION
**Pull request by whoot**
Gives to possibility for a user to choose between mOTP and Google authenticator.

googleauth.py goes to /raddb/scripts/
googleauth goes to /raddb/modules/

### CODE REVIEW

**Comment by doktornotor** [comment]
Should probably work with ```/usr/local/bin/python2.7``` shebang on 2.2.5+ since python is already there?

**Comment by cavy77** [comment]
Hi! Did you succeed in patching pfSense FreeRADIUS to integrate Google Authentication?
I'm new to GitHub: how could I download the latest version of the files and try it?
I'm in the latest version of pfSense (2.2.4) and FreeRADIUS 2.
Thank you in advance!

**Comment by whoot** [comment]
Indeed it can work, when changing the shebang to /usr/local/bin/python2.7.
However the change in "freeradius.inc" at line 512 seems to be not working.
Since i am not a PHP programmer, i dont know what the issue is, but im tipping on a missing reference to the varusersauthmethod. It would be great, if someone could help me out with this.

As a workaround you can just change the "motp" in line 512 to "googleauth". Works perfect, but you cant use "motp" anymore. If you just use googleauth, this is not a problem.

**Comment by Trozz** [comment]
any update on this?

**Comment by michaeleino** [comment]
Any update for this great package??

**Comment by cbuechler** [comment]
This is easier to merge now that python is in base, but 2.2.x and earlier packages are no longer supported, and it's best for sake of the history and to ease cherry-picking to have it in a single commit. 

@whoot if you could please update for 2.3 and re-submit to the FreeBSD-ports repo, we'll get that merged promptly. Thanks!

**Comment by grizmin** [comment]
patch for 2.3

https://gist.github.com/grizmin/f9b704f3406f33ffe9979208945fe659

**Comment by whoot** [comment]
Alright, i finally got it and will publish a pull request to the repository in a few days

**Pull request closed without merging**
