### PR TITLE
Update BIND to point to correct Log location

### PR DESCRIPTION
**Pull request by sharkbit**
Updated BIND Log location:
From:  diag_logs_resolver.php
To:      status_logs.php?logfile=resolver

### CODE REVIEW

**Comment by sharkbit** [comment]
Bug Report:  https://redmine.pfsense.org/issues/7431

**Comment by netgate-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by sharkbit** [comment]
CLA Signed

**Comment by rbgarga** [comment]
This repository is not being maintained anymore since it's not used by current pfSense stable version (2.3). If you want to submit patches for current packages please do it on https://github.com/pfsense/freebsd-ports

**Pull request closed without merging**
