### PR TITLE
nut: add generic nutdrv_qx driver

### PR DESCRIPTION
**Pull request by grawity**
Works slightly better than blazer_usb for various UPSes based on "Viewpower" or "Voltronic".

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by cbuechler** [comment]
Thanks @grawity, I merged this to the 2.3 package.

**Comment by grawity** [comment]
Thanks, I can't seem to find it in the repo though? Or do 2.3 packages live elsewhere now?

**Comment by grawity** [comment]
Ah, nevermind – I found the "FreeBSD-ports" repo.

**Pull request closed without merging**
