### PR TITLE
Add privileges configuration to squidguard package

### PR DESCRIPTION
**Pull request by doktornotor**
Hey guys, kindly check that whatever thing that parses this swallows multiple &lt;conflicts&gt; tags per package. Couldn't find any code anywhere regarding this - at all.

### CODE REVIEW

**Comment by doktornotor** [comment]
If this cannot be done, I'm frankly inclined to stick some hacks into custom_php_install_command() to cause the package install to fail if conflicting packages are found. These things mess up each other, and mess up non-matching Squid versions badly.

**Comment by rbgarga** [comment]
Please use a single conflicts tag with all items separated by space. I'll take care of introducing necessary checks. Thanks!

**Comment by doktornotor** [comment]
OK, I'll redo this shortly, thanks :)

**Comment by doktornotor** [comment]
Hmmm... "separated by space" is rather unfortunate when the name tags have spaces in package names. WTF. Should this be quoted (single, double) or what? Sigh.

**Comment by rbgarga** [comment]
Yeah, you are right @doktornotor. Let it as is, with multiple conflicts tags, and I'll take care and change the script that creates 2.3 ports

**Comment by doktornotor** [comment]
Well, another alternative would be renaming the packages (this was a very bad idea in the first place to allow spaces there) but definitely too late for that.

**Comment by rbgarga** [comment]
I'm working to merge this one, but I reverted conflicts changes for now. This tag conflicts is only used by the script that convert a 2.2 package into a 2.3 port on repo FreeBSD-ports, and since we are not converting all those packages versions to 2.3, we don't need to do it.

The only method 2.2 has to control conflicts is based on tag internal_name, and this is not enough unfortunately to cover all those cases you figured out. It's too late to make a big change on 2.2, lets concentrate to have a better package system on 2.3

Thanks once again for all your contributions!!!

**Comment by doktornotor** [comment]
OK... I guess I'll do a new PR to add some warnings into package descriptions instead, I guess that'd be OK and cause no compatibility issues, also doesn't require any changes elsewhere.

Thanks. :)

**Pull request merged**
