### PR TITLE
Disable strikeback package on 2.2 (for real now)

### PR DESCRIPTION
**Pull request by doktornotor**
This package is completely broken, calling pkg_add/pkg_delete, generally WTF code.

### CODE REVIEW

**Comment by jim-p** [comment]
Even better -- just remove it from this file entirely, since 2.1.x can't/won't read this file. :-)

**Comment by doktornotor** [comment]
OK, guys. Someone please hide the *beep* from people in whatever manner you find appropriate. I meant to keep it there in case someone eventually might get mad enough to fix the thing (definitely NOT myself), and it felt wrong to have required version higher than max. version. So, it was not to suggest that 2.1.x should read this file.

**Comment by jim-p** [comment]
OK, fair enough. Usually in those cases we set the version requirements absurdly low or absurdly high and note in the comment to "fix/remove once the package has been unbroken" or something to that effect.

**Comment by doktornotor** [comment]
Ok, looks like done with cc096698 so closing this. Thanks again. :+1:

**Pull request closed without merging**
