### PR TITLE
apcupsd - fix e-mail notifications

### PR DESCRIPTION
**Pull request by dbaio**
- alter reference for PHPMailer. (PHPMailer was updated on mailreport package)
- bump version

### CODE REVIEW

**Comment by dbaio** [comment]
@josh4trunks  
only php code was fixed, on pfSense 2.1 it's working, but on pfSense 2.2 we have another problem, PBI related.

@arrmo 
with net and snmp drivers, it's ok on pfSense 2.2, but pcnet driver is broken.

I will write a summary on pfSense forum.

**Comment by arrmo** [comment]
Sorry, not being a driver expert (OK, an idiot really) ... USB is not working. Is this part of pcnet?

Thanks!


PS: I have a posting on the pfSense forum about this already. Want to add to that?

**Comment by dbaio** [comment]
@arrmo   It's another drive.
Also USB doesn't work either.  
Thanks.
I've made a new post: 
 https://forum.pfsense.org/index.php?topic=89901.0

**Comment by josh4trunks** [comment]
@arrmo
USB connection to my APC UPS works on pfsense 2.2
the only thing not working for me are the email alerts.

**Comment by arrmo** [comment]
Hmmm ... not working for me. Need to dig into it, it seems.

Thanks!

**Comment by dbaio** [comment]
@josh4trunks   Could you inform the UPS model ? 
I will put a note on the forum.
Thanks.

**Comment by josh4trunks** [comment]
I think I have a ES 550VA.

**Pull request merged**
