### PR TITLE
Add privileges configuration to packages - part 1

### PR DESCRIPTION
**Pull request by doktornotor**
This adds configurable privileges for packages to System - User Manager.

### CODE REVIEW

**Comment by pfSense-git-updates** [comment]
Before this pull request can be accepted you must first sign a CLA as described at https://www.pfsense.org/about-pfsense/#cla. Please read for more details.

**Comment by doktornotor** [comment]
Huh? How many times should I sign it?

**Comment by rbgarga** [comment]
@doktornotor please ignore the message, we are testing a script to automatically add these messages and set labels, but it still needs some fixes

**Comment by doktornotor** [comment]
Ah, OK... :)

**Pull request merged**
