### PR TITLE
Fix: Squid RealTime stat 1.20 for the proxy server (unknown) (x.x.x.x:3128).

### PR DESCRIPTION
**Pull request by ReinaldoFeitosa**
Error (1): Cannot get data. Server answered: HTTP/1.1 403 Forbidden

Lines comment is not necessary.

### CODE REVIEW

**Comment by doktornotor** [comment]
Uhm... when you get forbidden, perhaps fix the ACLs instead of hardcoding localhost? What if Squid is not running on localhost?

**Comment by ReinaldoFeitosa** [comment]
But IP interface does not solve the Squid is on another host.
What is the purpose of taking the ip of all interfaces? all are equal localhost.

**Comment by cbuechler** [comment]
His point is you don't have to bind squid to 127.0.0.1. Nor should the port be hard coded. There may be a problem of some sort here, but if there is, this isn't a fix. Those lines aren't unnecessary.

**Comment by ReinaldoFeitosa** [comment]
The code just takes the last listed interface on squid.
If you are instaldo on another host will give the same problem.

**Pull request closed without merging**
