### PR TITLE
Bug #4583 - Squid3 breaking /etc/inc/captiveportal.inc

### PR DESCRIPTION
**Pull request by doktornotor**
Remove the broken patching nonsense that damages core OS files; reference: https://forum.pfsense.org/index.php?topic=91435.0 and many other threads on the forum.

### CODE REVIEW

**Comment by doktornotor** [comment]
Regarding the second batch of commits trying to undo the b0rkage -- honestly unsure whether it's worth the trouble.

**Comment by marcelloc** [comment]
Doktornoton, this was already fixed when I helped garga to cleanup squid3 package on 2.2.
Without patching captive portal, squid port keeps open for unauthenticated captive portal users.

**Comment by marcelloc** [comment]
And there is a backup file before any changes.

$pfsense_version=preg_replace("/\s/","",file_get_contents("/etc/version"));
if (!file_exists('/root/'.$pfsense_version.'.captiveportal.inc.backup')) {

copy ($cp_file,'/root/'.$pfsense_version.'.captiveportal.inc.backup');

**Comment by doktornotor** [comment]
@marcelloc: "Without patching captive portal, squid port keeps open for unauthenticated captive portal users." 

And WITH patching the file, you completely break the CP it by inserting thousands of empty lines into it.. Please, read the linked forum thread. Sorry, this ain't a viable way to do things.

**Comment by marcelloc** [comment]
until 0.2.8 package version, there bug was an extra "\n" on the patch and it was removed.

I'll do a clean install to teste it again. The forum thread is from april.

**Comment by marcelloc** [comment]
https://github.com/pfsense/pfsense-packages/commit/f9b65f8e27cbc3ae7028d094c70cdc9f38e19523
IMHO it's better fixing it instead of removing it.

**Comment by doktornotor** [comment]
Well yes, of course. But the proper way to fix it is to produce a generic function which allows packages to insert ipfw rules into the CP if they need such thing. There are more proxy packages that can do nontransparent proxy on pfSense than just Squid. So those are broken in the same way, allow CP bypass in the same way and definitely cannot be fixed by another patching of captiveportal.inc, since this gets out of the hands completely even with two packages trying to do this.

**Pull request closed without merging**
