### PR TITLE
fix OSPF authentication

### PR DESCRIPTION
**Pull request by trendchiller**
fix OSPF authentication

### CODE REVIEW

**Comment by trendchiller** [comment]
fix and bump

**Comment by doktornotor** [comment]
Uhm... I've redone this in #1035 since this has broken indentation and generally would produce conflict one or the other way.

**Comment by trendchiller** [comment]
This is indeed bad. 
Without this authentication, ospf is not usable at all.
:-(
What you please check what the conflicts are ? Regards,
Martin

**Comment by doktornotor** [comment]
I guess we are not understanding each other? I have included your changes in my pull request, so once it gets done, all is OK here.

(Your accidental commits and reverts to hundreds of unrelated files due to those branch merges are not acceptable anyway.)

**Comment by doktornotor** [comment]
No, not really, things are way too hectic ATM due to the bootstrap stuff; normally takes a week or so. You can use system patches package meanwhile.

**Comment by trendchiller** [comment]
Yes, sounds reasonable. 
So if your fixes are identically I'll be happy ;-)

**Comment by doktornotor** [comment]
The resubmit of your fixes is here: b80560f738cd90d68f5ba3ac8587e0990f282e1f

**Comment by doktornotor** [comment]
That PR needs to be merged by pfSense developers. No different from yours.

**Comment by trendchiller** [comment]
Ok, I see !
Then everything will be alright ;-)
Btw: are you the drnotor from the qnap-forum ?

**Comment by doktornotor** [comment]
Well yeah, though no longer there due to general idiocy. Occasionally visit the qnap.community forum.

**Comment by trendchiller** [comment]
Correct ;-)
I have seen the page, but no deep dive until now ...
I'll check later ...

**Pull request closed without merging**
