### PR TITLE
add "dev" option for inline config

### PR DESCRIPTION
**Pull request by ledowong**
so it works on both iOS and Tunnelblick

### CODE REVIEW

**Comment by doktornotor** [comment]
What problem are you solving here? It already works when you export it in the *proper* format.

**Comment by ledowong** [comment]
Which format is *proper* for Tunnelblick?

I guess 'dev' option is common in inline config file.
I tried Synology build-in OpenVPN, [OpenVPN Virtual Appliances](https://openvpn.net/index.php/access-server/download-openvpn-as-vm.html) and ASUS router build-in OpenVPN, all their config file with 'dev' option.

I see no harm to include 'dev' option back to inline config file. It doesn't break iOS/Andriod. It just make the config file compatible with more client. Btw it was [there](https://github.com/pfsense/pfsense-packages/commit/34664d0519236cd45ab223963edb2e87aa175804).

**Comment by doktornotor** [comment]
That's what not what you have patched there. You have changed not only the dev- option. Now, you also dump tun-ipv6 in all  inline configurations.

**Comment by jim-p** [comment]
The original change you commented on was two and a half years old. We've used the clients in question since then without problems. Perhaps there is something else wrong in your client/config, or you used the wrong format. Either way, as has been pointed out, the change in this pull request does much more than stated. This needs some discussion on the forum and much more agreement before being pulled in.

**Comment by ledowong** [comment]
I afraid I am using the correct client/config (inline config for Tunnelblick), following [this](https://doc.pfsense.org/index.php/OpenVPN_Client_Export_Package) document.

>**Inline Configurations**
>* Others: Exports an inline configuration file suitable for use by any other current OpenVPN client, such as the Windows client, Viscosity, or Tunnelblick.
>
>**Mac OSX**
>The current versions of Viscosity and Tunnelblick also import Inline configurations properly.

But it doesn't work. It might be [Tunnelblick](https://tunnelblick.net/downloads.html) make some changes in this two and a half years, I am not sure, I am using version 3.5.3.
Base on the log from Tunnelblick, it said 'dev' option is needed. So I edit the config file, add 'dev' option, and it works.

Yea @doktornotor is right, I shouldn't touch 'tun-ipv6', or maybe android as well. Thanks.

**Pull request closed without merging**
