### PR TITLE
ntopng - reworked package

### PR DESCRIPTION
**Pull request by doktornotor**
ntopng.xml 
- Moved all PHP code to separate ntopng.inc
- Add a button to wipe ntopng data
- Add enable checkbox
- Add checkbox to either keep or delete settings and data on uninstall/reinstall.
- Some description cosmetics

ntopng.inc (added)
- Moved all PHP code here; hopefully should fix most of the whacky issues mentioned in Bug #4880
- Add wipe data feature
- Add minimum password length check
- Optionally wipe all traffic data, graphs and settings on uninstall if so configured

### CODE REVIEW

**Comment by rbgarga** [comment]
You renamed password fields, old values are going to get lost during upgrade, no?

**Comment by doktornotor** [comment]
Old value got lost, like - always. The install either failed, or has overwritten the settings with some CSRF crap.

**Comment by cbuechler** [comment]
Merged. 

@rbgarga could you get the PBI updated please? https://redmine.pfsense.org/issues/4831

**Comment by rbgarga** [comment]
ntopng is marked as BROKEN on FreeBSD ports tree since the last update of net/ndpi. I pushed a fix to pfPorts and will build a new PBI

**Comment by rbgarga** [comment]
@doktornotor new PBIs available:
http://files.pfsense.org/packages/10/All/ntopng-1.2.1_3-amd64.pbi
http://files.pfsense.org/packages/10/All/ntopng-1.1_2-i386.pbi
Can you check them please?

**Comment by doktornotor** [comment]
Hmmmm... The new package seems to be completely missing fonts, among other things.

**Pull request merged**
