### PR TITLE
Allow to select OSPF Network Type in the Quagga OSPFd > Interface Set…

### PR DESCRIPTION
**Pull request by agpecam**
…tings

To run OSPF over OpenVPN/TUN between RouterOS (client) and pfSense (server) I have to set OpenVPN-interface-network-type to 'Point-To-Point' on both sides, having "...netmask mismatch" otherways.
Two confusing things: 1) I do not know what network type is default to Quagga OSPFd, so my default is 'not specified'. 2) Name and description of my drop-down box for English is not my native language.
Thanks.

### CODE REVIEW

**Comment by jim-p** [comment]
In looks OK but you'll need to bump the package version in the manifest and in the package's .xml file.

Can you also submit this against the copy of the package in our freebsd-ports repository? The packages have diverged a bit so changes have to be done both places (or, preferably, only on the copy in our freebsd-ports repo)

**Comment by agpecam** [comment]
Sorry, the package's .xml files have different versions in pfsense/pfsense-packages repository.
quagga_ospfd.xml - 0.6.9
quagga_ospfd_interfaces.xml and quagga_ospfd_raw.xml - 0.6.6
Should I bump them all to 0.6.10? I am in doubt.

**Comment by jim-p** [comment]
We're working on simplifying all of that. For the moment only worry about bumping the Makefile.

**Comment by jim-p** [comment]
(That's for the 2.3 version) -- for the pfsense-packages repo just update the main one, quagga_ospfd.xml for now

**Pull request merged**
