### PR TITLE
Added Clamd log tab to GUI

### PR DESCRIPTION
**Pull request by SunStroke74**
As addition to ability to switch "libclamav <-> clamd", we need tab to view clamd logs.

PS. Last of my "libclamav <-> clamd" series patches for HAVP.

### CODE REVIEW

**Comment by rbgarga** [comment]
Please bump package version then users can see the new version is available

**Comment by rbgarga** [comment]
This PR cannot be automatically merged, please rebase your fork

**Comment by SunStroke74** [comment]
I am not so well familiar with github...
Tried to update my fork base from upstream (as described at http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/). Is this enough?

**Comment by rbgarga** [comment]
Unfortunately not, PR cannot be automatically merged yet. If you are more comfortable sending a fresh Pull Request and closing this one, it's OK.

**Comment by doktornotor** [comment]
@SunStroke74 I'm pretty such I completely ruined any chance of rebasing with recent code style cleanup. Want me to redo and resubmit this? 

Note; split() is deprecated. Use explode() or something.

**Comment by doktornotor** [comment]
Resubmitted as PR #1055 due to conflicts. Please, close this.

**Pull request closed without merging**
