### PR TITLE
haproxy-devel, small fixes for showing/hiding acl fields, fix custom action, pkg v0.36

### PR DESCRIPTION
**Pull request by PiBa-NL**
haproxy-devel, small fixes for showing/hiding acl fields not applicable, fix custom action, pkg v0.36

### CODE REVIEW

**Comment by rbgarga** [comment]
Are you going to send similar changes to 2.3?

**Comment by PiBa-NL** [comment]
I am working on some 2.3 changes a.t.m. actually using the form classes and bootstrap stuff..
From what i read the packages should currently still sync over to the ports branche automatically.?

Next pull request will set maximum version to 2.2.999 which should stop that. If i understood correctly.

**Comment by rbgarga** [comment]
We are not running sync script anymore, if you need it in this case it' s fine to call it just for this package. I was just checking to be sure

**Comment by PiBa-NL** [comment]
Ok, well then it doesn't matter for me, ill be including these changes in the 2.3 pull-requests ill send in a few days.

**Pull request merged**
