### PR TITLE
Backup package code style

### PR DESCRIPTION
**Pull request by phil-davis**
I thought I might as well quickly format these little packages also, just so they are done if anyone else ever touches them again. I will look at a couple more like:
blinkled
gwled
LCDproc (maybe)
mailreport
Shellcmd

They seem to be the little packages that are easy and are mostly maintained internally when needed.

### CODE REVIEW

**Comment by doktornotor** [comment]
Well, shellcmd is full of copy-paste disfuntional WTF crap (empty "functions" commented out, some "service" (does not do any service at all) etc. If you want to clean it up, feel free. 

Blinked I did a few days ago, alas apparently the wrong packge. Why do we have two I don't understand. Will redo it now. Sigh.

**Comment by phil-davis** [comment]
I am trying to ignore empty crud... I don't want to break stuff, just quickly format it. If I notice anything that would actually be broken (rather than just NULL) then I care a little bit.

**Comment by cbuechler** [comment]
Always glad to get even style-only fixes, thanks @phil-davis. 

Also thanks @doktornotor for all your package contributions of late. 

We're trying to keep up with the pull requests, but been buried in other work as well this week so a bit slower than I'd like getting things in. 

merged.

**Comment by phil-davis** [comment]
No problem - this sort of crud can sit waiting for a while and it is not stuff that gets touched often, so low chance of merge conflicts.

**Pull request merged**
