### PR TITLE
pfBlockerNG - Update MaxMind CC Archive

### PR DESCRIPTION
**Pull request by BBcan177**
Add new MaxMind "Anonymous Proxy and Satellite Providers" data.

### CODE REVIEW

**Comment by rbgarga** [comment]
Please bump package version so users can see a new version is available

**Comment by BBcan177** [comment]
This is only needed for new installations. Existing installs don't need to upgrade. This MaxMind archive is only required if the Users attempt to download from the MaxMind Web site fails, so a version bump is not required.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Renato BotelhoSent: Monday, February 9, 2015 6:30 AMTo: pfsense/pfsense-packagesReply To: pfsense/pfsense-packagesCc: BBcan177Subject: Re: [pfsense-packages] pfBlockerNG - Update MaxMind CC Archive (#812)Please bump package version so users can see a new version is available

—Reply to this email directly or view it on GitHub.

**Comment by BBcan177** [comment]
@rbgarga. Do you have any other concerns with this PR?

**Comment by rbgarga** [comment]
no, will merge it

**Pull request merged**
