### PR TITLE
snort, fix config-sync to 'system backup server'

### PR DESCRIPTION
**Pull request by PiBa-NL**
snort, fix config-sync to 'system backup server'

### CODE REVIEW

**Comment by rbgarga** [comment]
@bmeeks8 can you please take a look at this patch?

**Comment by bmeeks8** [comment]
I see no problem with the patch except now with the recent merge of my "3.2.7" update the version number for this patch would need to change to 3.2.8.  Alternatively, it is probably OK to leave the version the same (at 3.2.7) and folks impacted who wanted the update could simply do a GUI package reinstall.

**Comment by doktornotor** [comment]
When you are already touching this, mind fixing the instances of ```$snort_sync[row]``` -> ```$snort_sync['row']``` as well a couple of lines above? (One of the endless copies of marcelloc's XMLRPC sync code in the repo, all of which are slowly diverting from each other and have different level of bugs/lack of validation. Sigh... https://forum.pfsense.org/index.php?topic=61586.msg548518#msg548518)

**Comment by rbgarga** [comment]
Done @doktornotor

**Pull request merged**
