### PR TITLE
Add information on power consumption, if available

### PR DESCRIPTION
**Pull request by oobayly**

### CODE REVIEW

**Comment by rbgarga** [comment]
In order to get patches applied you must sign Individual or Corporate CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by rbgarga** [comment]
@oobayly In order to get patches applied you must sign Individual or Corporate CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by rbgarga** [comment]
CLA not signed, if you change your mind and decide to sign it, it can be re-opened

**Comment by topper727** [comment]
What if I will want this.. I signed and done patches..I looked over the code can I submit it?

**Comment by rbgarga** [comment]
Sure

**Pull request closed without merging**
