### PR TITLE
Modified to use the BGPd daemon with the Quagga package.

### PR DESCRIPTION
**Pull request by yuki**
This is a commit to use the BGPd daemon in the pfsense interface for the Quagga package

### CODE REVIEW

**Comment by yuki** [comment]
Does anyone seen this patch? Could we do something more to help to merge this pull request to the project?

Thanks

**Comment by jim-p** [comment]
We have seen it, yes, but we have not yet had an opportunity to test it out to confirm it works.

**Comment by rbgarga** [comment]
@yuki in order to have this applied, you must sign a CLA as described at https://www.pfsense.org/about-pfsense/#legal

**Comment by yuki** [comment]
I didn't watch that you updated my pull-request :disappointed: 

I have signed the CLA, and the order references is: 4Y3VF

I hope you can merge it soon. 

Thanks! :smile:

**Comment by nemesix29** [comment]
Hello,

When this pull request must be merged in master ?

**Comment by jim-p** [comment]
The request can't be merged cleanly at the moment, the original submitted will need to update their fork and fix any potential conflicts so it can be merged cleanly.

**Comment by cbuechler** [comment]
2.2.x and earlier packages are no longer being maintained, this has conflicts that need resolving and needs updating for 2.3. Please re-submit on the FreeBSD-ports repo updated for 2.3 and we can get that merged promptly. Thanks!

**Pull request closed without merging**
